### ISSUE TITLE
Oval button

### ISSUE THREAD

**Issue by nglaeser** [nglaeser/CybersecSite#11]
The arrow button on the home page is oval; needs to be a circle.

**Comment by clayscode** [comment]
![circlenotoval](https://user-images.githubusercontent.com/16871737/33440883-2b75bc6a-d5bf-11e7-8e53-1615faeee8c0.gif)
 Relevant Gif

**Comment by nglaeser** [comment]
Fixed in [4395d6d](https://github.com/nglaeser/CybersecSite/commit/4395d6db9c643fcdeff57f5c649943e54ab93826)
