### ISSUE TITLE
Events page "contact" button (at bottom)

### ISSUE THREAD

**Issue by nglaeser** [nglaeser/CybersecSite#15]
"Contact" button in the "Call to action" section needs to be centered and the margin to the footer needs to be increased.

**Comment by nglaeser** [comment]
Bottom padding/margin fixed. Button still has to be centered.

**Comment by jyn514** [comment]
I'm thinking of making contact a hyperlink on 'let us know'. Think it would look more elegant

**Comment by jyn514** [comment]
Done in https://github.com/nglaeser/CybersecSite/commit/82bf1c36d9bb351732378cb7b292a528001f55b1
