### ISSUE TITLE
Fix docker support

### ISSUE THREAD

**Issue by jyn514** [nglaeser/CybersecSite#19]
# Problem description
Site gives only a TCP RST packet when run from docker. Works fine when run with `python app.py`

# Steps to reproduce (if applicable)
`docker-compose up`
Navigate to localhost:5000

# Desired outcome
Have site be visible when run with docker

See also https://github.com/nglaeser/CybersecSite/pull/17

**Comment by clayscode** [comment]
app.run() just needs to be changed to app.run(hot='0.0.0.0') in app.py
