### ISSUE TITLE
Buy domain name

### ISSUE THREAD

**Issue by jyn514** [nglaeser/CybersecSite#21]
Club chose cyberusc, extension is open. I heard @nglaeser saying [namecheap](https://www.namecheap.com/domains/registration/results.aspx?domain=cyberusc) had it for ~$11 and [internetbs](https://internetbs.net/en/domain-name-registrations/Internet_Domain_Registration_Search.html) had it for ~$8, but they're less reputable.

**Comment by jyn514** [comment]
Think we decided to go with usccyber.club instead. Peyton has final say.

**Comment by nglaeser** [comment]
## Domain Prices per year

| | [porkbun](https://porkbun.com) | [namecheap](https://www.namecheap.com/domains.aspx) | [Google Domains](https://domains.google.com/)
|---|---|---|---|
|usccyber.club | $9.57/renew $9.23 | $0.77/renew $10.88| $13 |
|cyberusc.com | $8.84 | $10.98| |
|cyberusc.org | $10.72 | $12.98| |
|usccyber.org | $10.72 | $12.98| $12 |

**Comment by jyn514** [comment]
Done. Address is http://www.usccyber.org
