### ISSUE TITLE
Add events section

### ISSUE THREAD

**Issue by jyn514** [nglaeser/CybersecSite#31]
The events page doesn't have a section for events. I was trying to add Big Wednesday and it looked awful. Should setup a event section that looks decent.

**Comment by nglaeser** [comment]
I can get this. What kind of events are you planning on listing? Big Wednesday, ... (E-week? what else?)

**Comment by nglaeser** [comment]
Thinking of adding back the multicolored tiles that used to be on the "About" page to highlight types of recurring events

**Comment by jyn514** [comment]
Big Wednesday, e-week, competitions we plan on competing in. The calendar is decent for the club, but it doesn't really describe what the events are.

**Comment by nglaeser** [comment]
Details to be filled in but the outline is there. How is it?

**Comment by jyn514** [comment]
Looks nice. Like how the color scheme matches. I am a little worried we'll run out of space, maybe we could make the events headers like a dropdown that change the look of the page?

I'm not explaining it well, I'll explain it in person next meeting.
