### ISSUE TITLE
Make mail logo smaller

### ISSUE THREAD

**Issue by jyn514** [nglaeser/CybersecSite#5]
Mail logo introduced in https://github.com/nglaeser/CybersecSite/commit/ad3b105090abe612cb060b3e80650729c84f3f5b doesn't match other logos. Would be nice to fix it.

**Comment by jyn514** [comment]
Fixed in https://github.com/nglaeser/CybersecSite/commit/8843c0d7c5fad610531338e408c0db8e1874d6f7

**Comment by nglaeser** [comment]
I thought I did this? Or maybe we came to the same conclusion at the same time. Anyway, lots of other useful icons here as well: http://ionicons.com/cheatsheet.html

EDIT: Oh, I see what you did. Never mind.
