### ISSUE TITLE
Add officer info to about page

### ISSUE THREAD

**Issue by jyn514** [nglaeser/CybersecSite#7]
for the about page

**Comment by jyn514** [comment]
Les  - VP
Chris Welborn  - Secretary
William Edwards  - CTF Coordinator
Peyton Chandarana - Treasurer

Everyone else has sent me photos

**Comment by jyn514** [comment]
Would like to have brief description and photo from officers. Nothing fancy, just 'I like to do such and such' (Charles would say something like 'create endless layers of bash scripts')

**Comment by jyn514** [comment]
Looks bad to have half with, half without. Assigning @nglaeser since you've mostly been dealing with it anyways.

**Comment by nglaeser** [comment]
Make picture grid, all same size.
